// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  module.exports = function(validation) {
    var moirai;
    return moirai = {
      add_team_asset: function(actor, team) {
        return moirai._can_manage_moirai_assets(actor, team);
      },
      remove_team_asset: function(actor, team) {
        return moirai._can_manage_moirai_assets(actor, team);
      },
      _is_moirai_team_admin: function(actor, team) {
        return validation.auth._is_team_admin(actor, team);
      },
      _can_manage_moirai_assets: function(actor, team) {
        return validation.auth.kratos._is_kratos_admin(actor) || moirai._is_moirai_team_admin(actor, team);
      },
      proxy: {
        start: function(actor, team) {
          return moirai._can_manage_moirai_assets(actor, team);
        },
        stop: function(actor, team) {
          return moirai._can_manage_moirai_assets(actor, team);
        }
      }
    };
  };

}).call(this);
