// Generated by IcedCoffeeScript 1.8.0-e
(function() {
  module.exports = function(validation) {
    return {
      add_team_asset: function(team, asset) {},
      remove_team_asset: function(team, asset) {}
    };
  };

}).call(this);
